# Generated by Django 4.2.7 on 2023-11-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate_app', '0001_initial'),
        ('hr_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=30)),
                ('is_manager', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.department')),
                ('hr_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.hr')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('jobId', models.AutoField(primary_key=True, serialize=False)),
                ('jobRole', models.CharField(max_length=200, unique=True)),
                ('JobLevel', models.IntegerField()),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('LocationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate_app.location')),
                ('departmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(default='HR', max_length=200)),
                ('teamMem', models.IntegerField(default=0)),
                ('manager', models.CharField(max_length=200)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('wordId', models.AutoField(primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employee')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leaveId', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveType', models.CharField(max_length=200)),
                ('StartDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('NoOfHours', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('empEmail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='jobRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.jobrole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate_app.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.team'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cirId', models.AutoField(primary_key=True, serialize=False)),
                ('CirTitle', models.CharField(max_length=200)),
                ('Technology', models.CharField(max_length=200)),
                ('EarnDate', models.DateField(null=True)),
                ('Expdate', models.DateField(null=True)),
                ('empEmail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
