# Generated by Django 4.2.7 on 2023-11-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('conId', models.AutoField(primary_key=True, serialize=False)),
                ('conName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regId', models.AutoField(primary_key=True, serialize=False)),
                ('regName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locId', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
                ('conid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate_app.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='regId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate_app.region'),
        ),
    ]
